set(linuxdeployqt_GIT_REF 472f7c50f8eab5e29a65436ed15a3eff2c913379)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/linuxdeployqt
    REF ${linuxdeployqt_GIT_REF} # or use a specific tag/commit
    SHA512 02d903bf63b30f87aed3a9cdc4fde45fd4c1ddf337c12d5e91b604e4c64f4b1a2f4c1c2900e18f9f0b91ff4894388f586b22e518ad20e3b3f6e90d31208ad53e # Replace with the actual sha512 generated by vcpkg hash
)

if (NOT CMAKE_HOST_UNIX)
    message(FATAL_ERROR "linuxdeployqt is only supported on Linux.")
endif()

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DGIT_TAG_ID=${linuxdeployqt_GIT_REF}
)

vcpkg_cmake_install()
#vcpkg_cmake_config_fixup()
