set(libqxt_GIT_REF 5faf678eb01ee63efd7f424fdbc78976cc67f879)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO drescherjm/libqxt-cmake
    REF ${libqxt_GIT_REF} # or use a specific tag/commit
    SHA512 55635387b874b78c3b4b1235b7781a47b9d61ff3c6bfdbd1a459ab79cb795b52a43ffd5e71487e9a5e3a2f95a1cc0dc6722fd79b26ac83a45632ee7b117d7057 # Replace with the actual sha512 generated by vcpkg hash
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_build()
vcpkg_cmake_install()

# Fixup cmake config locations and paths. This is essential for vcpkg to setup the SimpleLibraryExampleConfig.cmake file 
# and setup each configuration for multiconfig generators like Visual Studio 2022. 
# Remember that vcpkg builds the Debug and Release config then maps the other configs: MinSizeRel, RelWithDebInfo to
# use the binaries created for the Release config. 
vcpkg_cmake_config_fixup(PACKAGE_NAME libQxt CONFIG_PATH lib/cmake/libQxt)