message(STATUS QT_VERSION_MAJOR=${QT_VERSION_MAJOR}\n${PROJECT_NAME}_QT_VERSION=${${PROJECT_NAME}_QT_VERSION})

set (QT_LIBRARIES Qt${QT_VERSION_MAJOR}::Core Qt${QT_VERSION_MAJOR}::Widgets Qt${QT_VERSION_MAJOR}::Gui Qt${QT_VERSION_MAJOR}::Xml)
set (QT_MODULES Qt${QT_VERSION_MAJOR}::Core Qt${QT_VERSION_MAJOR}::Widgets Qt${QT_VERSION_MAJOR}::Gui Qt${QT_VERSION_MAJOR}::Xml)
set (QT_PLATFORM_MODULES Qt${QT_VERSION_MAJOR}::QWindowsIntegrationPlugin)

if(${PROJECT_NAME}_QT_VERSION VERSION_LESS "6")
	set( QT_LIBRARIES ${QT_LIBRARIES} Qt${QT_VERSION_MAJOR}::WinMain)
	set (QT_MODULES ${QT_MODULES} Qt${QT_VERSION_MAJOR}::WinMain)
else ()
	set( QT_LIBRARIES ${QT_LIBRARIES} Qt${QT_VERSION_MAJOR}::Core5Compat Qt${QT_VERSION_MAJOR}::StateMachine)
	set (QT_MODULES ${QT_MODULES} Qt${QT_VERSION_MAJOR}::Core5Compat Qt${QT_VERSION_MAJOR}::StateMachine)
endif()

find_qt5_packages()

find_package(QtBasicUtils REQUIRED)

find_package(libQxt CONFIG REQUIRED)